sudo: required
dist: bionic

language: python

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - chmod +x ./script/buzzer1.py
  - rostest pimouse_ros_tuto test.launch
